// SPDX-License-Identifier: GPL-3.0-only
package org.maiwithu.maicraft.intent;

import org.maiwithu.maicraft.client.server.MachineSnapshotEnrichmentTest;
import org.maiwithu.maicraft.client.server.ServerActorMutationGateTest;
import org.maiwithu.maicraft.client.server.ServerAssistanceRegressionSuite;
import org.maiwithu.maicraft.core.integration.ae2.Ae2ServerCraftJobTest;
import org.maiwithu.maicraft.core.integration.ae2.Ae2ServerSupplyTest;
import org.maiwithu.maicraft.core.integration.create.CreateEconomicEndpointBridgeTest;
import org.maiwithu.maicraft.core.integration.create.CreateExactUtilityEndpointTest;
import org.maiwithu.maicraft.core.integration.create.transmission.ChainConveyorContractTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticClearanceRevalidationTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticClientHeightmapTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticCogwheelGeometryTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticMaterialCostsTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticRouteChoiceTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticRouteContinuationTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticRouteGeometryTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticRpmBudgetTest;
import org.maiwithu.maicraft.core.integration.create.transmission.KineticTransmissionAlternativesTest;
import org.maiwithu.maicraft.core.integration.machine.MachinePlacementItemsTest;
import org.maiwithu.maicraft.core.integration.machine.catalog.MachineCatalogTest;
import org.maiwithu.maicraft.core.integration.machine.catalog.UtilityInstallationCatalogTest;
import org.maiwithu.maicraft.core.integration.machine.discovery.MachineDiscoveryScannerTest;
import org.maiwithu.maicraft.core.integration.machine.layout.MachineLayoutUtilityInputsTest;
import org.maiwithu.maicraft.core.integration.machine.production.ProductionDesignCompilerTest;
import org.maiwithu.maicraft.core.integration.machine.production.ProductionNativeEvidenceTest;
import org.maiwithu.maicraft.core.integration.machine.production.ProductionPressInputObstructionTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionConnectionResponsesTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionConnectionSurveyTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionConstructionProtectionTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionEventCursorTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionEvidenceWindowTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionFlowBudgetTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionIdleObservationTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionInteractionNavigationTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionObservationRangeTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionOutputMonitorTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionProcessingProgressTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionProgressWatchdogTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionReadScheduleTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionRunPlanBindingTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionSessionIdleExpiryTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionSessionRolloverTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionStartupTransitionTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionSupplyBudgetTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionSupplyHintsTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionSupplyPacerTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionSupplyStockTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionTransitBaselineTest;
import org.maiwithu.maicraft.core.integration.machine.runtime.ProductionWatchLifecycleTest;
import org.maiwithu.maicraft.core.integration.machine.utility.MachineSurvivalMaterialsTest;
import org.maiwithu.maicraft.core.integration.machine.utility.MachineUtilityInputsTest;
import org.maiwithu.maicraft.core.integration.machine.utility.UtilityConnectionPlannerTest;
import org.maiwithu.maicraft.core.integration.machine.utility.UtilityConnectionTaskGuardTest;
import org.maiwithu.maicraft.core.integration.machine.utility.UtilityExistingCableRouteTest;
import org.maiwithu.maicraft.core.task.build.PlacementSneakProjectionTest;
import org.maiwithu.maicraft.mcp.SemanticAbilityAvailabilityTest;
import org.maiwithu.maicraft.network.OptionalServerPayloadTest;
import org.maiwithu.maicraft.network.ProtocolRegressionSuite;
import org.maiwithu.maicraft.server.inventory.Ae2NativeCraftingCompletionTest;
import org.maiwithu.maicraft.server.machine.NativeInventoryRegressionTest;
import org.maiwithu.maicraft.server.machine.CreateConfigurationContractTest;
import org.maiwithu.maicraft.server.machine.ProductionRetentionTest;
import org.maiwithu.maicraft.server.machine.ServerNativeRegressionTest;
import org.maiwithu.maicraft.server.machine.connectivity.ChainConveyorConnectionPathTest;
import org.maiwithu.maicraft.server.machine.connectivity.ConnectionInspectionTest;
import org.maiwithu.maicraft.server.machine.connectivity.HopperConnectionInspectionTest;
import org.maiwithu.maicraft.server.machine.create.CreatePressInputInspectionTest;
import org.maiwithu.maicraft.server.machine.mekanism.MekanismResourceRegressionTest;
import org.maiwithu.maicraft.server.machine.watch.MachineWatchProgressTest;

/** 验证协议、原生资源和生产不变量；模组实际世界中的验收另行执行。 */
public final class OptionalServerRegressionSuite {
    public static void main(String[] args) throws Exception {
        CreateConfigurationContractTest.main(args);
        ProtocolRegressionSuite.main(args);
        OptionalServerPayloadTest.main(args);
        ServerAssistanceRegressionSuite.main(args);
        ProductionSessionRolloverTest.main(args);
        ProductionSessionIdleExpiryTest.main(args);
        MachineSnapshotEnrichmentTest.main(args);
        ServerActorMutationGateTest.main(args);
        SemanticAbilityAvailabilityTest.main(args);
        Ae2ServerSupplyTest.main(args);
        Ae2ServerCraftJobTest.main(args);
        ServerNativeRegressionTest.main(args);
        CreatePressInputInspectionTest.main(args);
        NativeInventoryRegressionTest.main(args);
        ProductionRetentionTest.main(args);
        Ae2NativeCraftingCompletionTest.main(args);
        MekanismResourceRegressionTest.main(args);
        ConnectionInspectionTest.main(args);
        // 原版漏斗跨模组供料按物品机制检查方向、锁定与精确准入，不再误用 Create 动力边，也不冒充真实流量。
        HopperConnectionInspectionTest.main(args);
        ProductionDesignCompilerTest.main(args);
        ProductionNativeEvidenceTest.main(args);
        ProductionPressInputObstructionTest.main(args);
        MachineProductionContractTest.main(args);
        ProductionEvidenceWindowTest.main(args);
        ProductionSupplyBudgetTest.main(args);
        ProductionSupplyStockTest.main(args);
        ProductionSupplyPacerTest.main(args);
        ProductionEventCursorTest.main(args);
        ProductionOutputMonitorTest.main(args);
        ProductionWatchLifecycleTest.main(args);
        ProductionRunPlanBindingTest.main(args);
        ProductionProcessingProgressTest.main(args);
        ProductionSupplyHintsTest.main(args);
        ProductionTransitBaselineTest.main(args);
        ProductionProgressWatchdogTest.main(args);
        ProductionIdleObservationTest.main(args);
        ProductionStartupTransitionTest.main(args);
        ProductionFlowBudgetTest.main(args);
        PlacementSneakProjectionTest.main(args);
        ProductionConstructionProtectionTest.main(args);
        ProductionInteractionNavigationTest.main(args);
        ProductionObservationRangeTest.main(args);
        ProductionReadScheduleTest.main(args);
        ProductionConnectionSurveyTest.main(args);
        ProductionConnectionResponsesTest.main(args);
        MachineCatalogTest.main(args);
        MachineDiscoveryScannerTest.main(args);
        MachineUtilityInputsTest.main(args);
        MachineSurvivalMaterialsTest.main(args);
        MachineLayoutUtilityInputsTest.main(args);
        UtilityInstallationCatalogTest.main(args);
        UtilityConnectionPlannerTest.main(args);
        UtilityExistingCableRouteTest.main(args);
        UtilityConnectionTaskGuardTest.main(args);
        CreateExactUtilityEndpointTest.main(args);
        CreateEconomicEndpointBridgeTest.main(args);
        KineticRouteGeometryTest.main(args);
        KineticTransmissionAlternativesTest.main(args);
        KineticCogwheelGeometryTest.main(args);
        KineticMaterialCostsTest.main(args);
        KineticRouteChoiceTest.main(args);
        KineticRpmBudgetTest.main(args);
        KineticClientHeightmapTest.main(args);
        MachinePlacementItemsTest.main(args);
        KineticClearanceRevalidationTest.main(args);
        KineticRouteContinuationTest.main(args);
        ChainConveyorContractTest.main(args);
        ChainConveyorConnectionPathTest.main(args);
        MachineWatchProgressTest.main(args);
        System.out.println("OptionalServerRegressionSuite: passed");
    }
}
