// SPDX-License-Identifier: GPL-3.0-only
package org.maiwithu.maicraft.core.pathing;

import baritone.pathing.calc.HeightPolicyTest;
import baritone.pathing.calc.PathSearchRegressionTest;
import baritone.pathing.movement.CollisionGeometryTest;
import baritone.pathing.movement.DiagonalHazardTest;
import baritone.pathing.movement.DoorPassageTest;
import baritone.pathing.path.AssistedFallOwnershipTest;
import baritone.pathing.path.PathTickBudgetTest;
import org.maiwithu.maicraft.client.actor.NativeConfirmationTest;
import org.maiwithu.maicraft.client.actor.PacketTickBudgetTest;
import org.maiwithu.maicraft.core.blueprint.BlueprintImportTest;
import org.maiwithu.maicraft.core.integration.create.ContraptionObstaclesTest;
import org.maiwithu.maicraft.core.integration.create.elevator.ElevatorCallLinksTest;
import org.maiwithu.maicraft.core.integration.create.elevator.ElevatorExitReplanTest;
import org.maiwithu.maicraft.core.integration.create.elevator.ElevatorFloorsTest;
import org.maiwithu.maicraft.core.integration.create.elevator.ElevatorGeometryTest;
import org.maiwithu.maicraft.core.integration.create.elevator.ElevatorRemoteStagingTest;
import org.maiwithu.maicraft.core.integration.create.elevator.ElevatorSessionTest;
import org.maiwithu.maicraft.core.integration.jetpack.FlightTraceTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackClearancePolicyTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackCourseTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackDynamicsTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackFastDescentTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackFlightTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackGroundModeTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackMotionTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackNativeEvidenceTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackSearchTest;
import org.maiwithu.maicraft.core.integration.jetpack.JetpackViewTest;
import org.maiwithu.maicraft.core.integration.jetpack.MovingFlightSessionTest;
import org.maiwithu.maicraft.core.integration.jetpack.RegionalFlightTest;
import org.maiwithu.maicraft.core.integration.physics.PhysicalObstacleSnapshotTest;
import org.maiwithu.maicraft.core.integration.physics.SableStructureBridgeTest;
import org.maiwithu.maicraft.core.integration.physics.ShipBoardingGeometryTest;
import org.maiwithu.maicraft.core.integration.physics.StructurePoseTest;
import org.maiwithu.maicraft.core.integration.physics.StructurePresentationTest;
import org.maiwithu.maicraft.core.pathing.baritone.BaritonePlayerFeetTest;
import org.maiwithu.maicraft.core.pathing.baritone.FallDamageBudgetTest;
import org.maiwithu.maicraft.core.pathing.baritone.FallLandingTest;
import org.maiwithu.maicraft.core.pathing.baritone.GroundMovementReplayTest;
import org.maiwithu.maicraft.core.pathing.baritone.GroundPathSmoothingTest;
import org.maiwithu.maicraft.core.pathing.baritone.NavigationActionPolicyTest;
import org.maiwithu.maicraft.core.pathing.baritone.NavigationCameraCourseTest;
import org.maiwithu.maicraft.core.pathing.baritone.NavigationHandoffTest;
import org.maiwithu.maicraft.core.pathing.baritone.NavigationPolicySnapshotTest;
import org.maiwithu.maicraft.core.pathing.baritone.NavigationProgressTest;
import org.maiwithu.maicraft.core.pathing.baritone.NavigationScaffoldPlacementPolicyTest;
import org.maiwithu.maicraft.core.pathing.baritone.SubmergedWaterTravelPolicyTest;
import org.maiwithu.maicraft.core.pathing.baritone.TravelJumpPhysicsTest;
import org.maiwithu.maicraft.core.pathing.baritone.TravelRunwayTest;
import org.maiwithu.maicraft.core.pathing.baritone.WaterBucketFallTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.AirRescueChoiceTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.AutomaticFallAdmissionTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.BoatCatchReplayTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.BoatLandingAssistTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.EmergencyWaterSelectionTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.ExistingLandingQueryTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.FallDeparturePreparationTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.LandingAssistDisplacementTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.LandingAssistTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.LandingSupplyCleanupTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.LandingSurfaceRulesTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.MissedLandingHandoffTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.NativeBucketLandingTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.PlannedWaterReflexTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.SharedLandingExecutionTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.WaterLandingReplayTest;
import org.maiwithu.maicraft.core.pathing.baritone.landing.WaterSurfaceExecutionTest;
import org.maiwithu.maicraft.core.pathing.transport.TransportIntentTest;
import org.maiwithu.maicraft.core.pathing.transport.TransportRuntimeTest;
import org.maiwithu.maicraft.core.pathing.transport.TransportTargetsTest;
import org.maiwithu.maicraft.core.pathing.util.ClientSurfaceHeightTest;
import org.maiwithu.maicraft.core.pathing.util.SwimAirBudgetTest;
import org.maiwithu.maicraft.core.task.acquire.AcquisitionProtectionTest;
import org.maiwithu.maicraft.core.task.build.BuildTraversabilityVerifierTest;
import org.maiwithu.maicraft.core.task.mine.MiningBatchTest;
import org.maiwithu.maicraft.core.task.mine.MiningToolRequirementTest;
import org.maiwithu.maicraft.core.task.mine.NaturalTreeSourceTest;
import org.maiwithu.maicraft.core.task.mine.NoPathVerdictTest;
import org.maiwithu.maicraft.core.task.move.MoveToContractTest;
import org.maiwithu.maicraft.core.task.move.MoveToTransportCompletionTest;
import org.maiwithu.maicraft.core.tools.perception.LocalFloorSenseTest;
import org.maiwithu.maicraft.entity.InputDriverTest;
import org.maiwithu.maicraft.intent.ElevatorTravelIntentTest;
import org.maiwithu.maicraft.intent.persistence.IntentStateStoreTest;
import org.maiwithu.maicraft.mcp.NavigationOverviewTest;
import org.maiwithu.maicraft.mcp.NearbyCollisionPerceptionTest;
import org.maiwithu.maicraft.mcp.PhysicalDeckSamplerTest;
import org.maiwithu.maicraft.mcp.PhysicalStructurePerceptionTest;

/** 生产算法的回归测试；真实移动和服务器确认仍需游戏会话。 */
// 导航相关回归的集合入口，逐个调用既有测试 main；不是扫描目录自动发现所有测试。
// 按下面明确列出的顺序运行导航相关检查，任何断言失败就中断。新增测试文件不会自动加入；落地补料的菜单检查另由 GuiRegressionSuite 运行。
public final class NavigationRegressionSuite {
    // 从输入预算到路径、落地、飞行和交通依次检查；异常直接向外传给 Gradle，让 check 失败。
    public static void main(String[] args) throws Exception {
        InputDriverTest.main(args);
        NavigationUseProtectionTest.main(args);
        PacketTickBudgetTest.main(args);
        RegionalTerrainTest.main(args);
        RegionalFlightTest.main(args);
        JetpackGroundModeTest.main(args);
        NavigationOverviewTest.main(args);
        ContraptionObstaclesTest.main(args);
        ElevatorFloorsTest.main(args);
        ElevatorTravelIntentTest.main(args);
        SwimAirBudgetTest.main(args);
        SubmergedWaterTravelPolicyTest.main(args);
        NavigationHandoffTest.main(args);
        // 同一个真实半楼梯落脚面必须在建造与寻路里使用相同的起点格，避免反复得到无法起步的路径。
        BaritonePlayerFeetTest.main(args);
        // 跌落路径只查已有缓冲物时先筛选候选，保留真实水面、伤害和碰撞验证。
        ExistingLandingQueryTest.main(args);
        // 寻路搭路继续遵守目标位置的修改许可，附近机器不再额外触发掉落预测检查。
        NavigationScaffoldPlacementPolicyTest.main(args);
        MiningBatchTest.main(args);
        NaturalTreeSourceTest.main(args);
        NoPathVerdictTest.main(args);
        MiningToolRequirementTest.main(args);
        LocalFloorSenseTest.main(args);
        BlueprintImportTest.main(args);
        IntentStateStoreTest.main(args);
        MoveToContractTest.main(args);
        MoveToTransportCompletionTest.main(args);
        PathSearchRegressionTest.main(args);
        HeightPolicyTest.main(args);
        PathTickBudgetTest.main(args);
        DoorPassageTest.main(args);
        DiagonalHazardTest.main(args);
        CollisionGeometryTest.main(args);
        NearbyCollisionPerceptionTest.main(args);
        NavigationProgressTest.main(args);
        GroundPathSmoothingTest.main(args);
        GroundMovementReplayTest.main(args);
        TravelJumpPhysicsTest.main(args);
        TravelRunwayTest.main(args);
        NavigationCameraCourseTest.main(args);
        NavigationActionPolicyTest.main(args);
        WaterBucketFallTest.main(args);
        LandingSurfaceRulesTest.main(args);
        NativeBucketLandingTest.main(args);
        WaterSurfaceExecutionTest.main(args);
        EmergencyWaterSelectionTest.main(args);
        AirRescueChoiceTest.main(args);
        WaterLandingReplayTest.main(args);
        SharedLandingExecutionTest.main(args);
        LandingSupplyCleanupTest.main(args);
        AutomaticFallAdmissionTest.main(args);
        FallDeparturePreparationTest.main(args);
        MissedLandingHandoffTest.main(args);
        LandingAssistDisplacementTest.main(args);
        PlannedWaterReflexTest.main(args);
        AssistedFallOwnershipTest.main(args);
        FallDamageBudgetTest.main(args);
        FallLandingTest.main(args);
        TransportTargetsTest.main(args);
        TransportRuntimeTest.main(args);
        TransportIntentTest.main(args);
        JetpackFlightTest.main(args);
        JetpackSearchTest.main(args);
        JetpackDynamicsTest.main(args);
        JetpackCourseTest.main(args);
        JetpackClearancePolicyTest.main(args);
        JetpackMotionTest.main(args);
        StructurePoseTest.main(args);
        SableStructureBridgeTest.main(args);
        PhysicalObstacleSnapshotTest.main(args);
        StructurePresentationTest.main(args);
        ShipBoardingGeometryTest.main(args);
        PhysicalStructurePerceptionTest.main(args);
        PhysicalDeckSamplerTest.main(args);
        JetpackViewTest.main(args);
        JetpackFastDescentTest.main(args);
        JetpackNativeEvidenceTest.main(args);
        MovingFlightSessionTest.main(args);
        FlightTraceTest.main(args);
        ElevatorGeometryTest.main(args);
        ElevatorCallLinksTest.main(args);
        ElevatorSessionTest.main(args);
        ElevatorExitReplanTest.main(args);
        ElevatorRemoteStagingTest.main(args);
        LandingAssistTest.main(args);
        BoatLandingAssistTest.main(args);
        BoatCatchReplayTest.main(args);
        NativeConfirmationTest.main(args);
        BuildTraversabilityVerifierTest.main(args);
        ClientSurfaceHeightTest.main(args);
        AcquisitionProtectionTest.main(args);
        NavigationPolicySnapshotTest.main(args);
        System.out.println("NavigationRegressionSuite: passed");
    }
}
